var dataFormat = {
      "text": 1, 
      "truncated": 1, 
      "in_reply_to_user_id": 1, 
      "in_reply_to_status_id": 1, 
      "favorited": 1, 
      "source": 1, 
      "in_reply_to_screen_name": 1, 
      "in_reply_to_status_id_str": 1, 
      "id_str": 1, 
      "entities": {
            "user_mentions": [
                  {
                        "indices": [
                              3, 
                              19
                        ], 
                        "screen_name": 1, 
                        "id_str": 1, 
                        "name": 1, 
                        "id": 1
                  }
            ], 
            "urls": 1, 
            "hashtags": 1
      }, 
      "contributors": 1, 
      "retweeted": 1, 
      "in_reply_to_user_id_str": 1, 
      "place": 1, 
      "retweet_count": 1, 
      "created_at": 1, 
      "retweeted_status": {
            "text": 1, 
            "truncated": 1, 
            "in_reply_to_user_id": 1, 
            "in_reply_to_status_id": 1, 
            "favorited": 1, 
            "source": 1, 
            "in_reply_to_screen_name": 1, 
            "in_reply_to_status_id_str": 1, 
            "id_str": 1, 
            "entities": {
                  "user_mentions": 1, 
                  "urls": 1, 
                  "hashtags": [
                        {
                              "text": 1, 
                              "indices": [
                                    130, 
                                    134
                              ]
                        }
                  ]
            }, 
            "contributors": 1, 
            "retweeted": 1, 
            "in_reply_to_user_id_str": 1, 
            "place": 1, 
            "retweet_count": 1, 
            "created_at": 1, 
            "user": {
                  "notifications": 1, 
                  "profile_use_background_image": 1, 
                  "statuses_count": 1, 
                  "profile_background_color": 1, 
                  "followers_count": 1, 
                  "profile_image_url": 1, 
                  "listed_count": 1, 
                  "profile_background_image_url": 1, 
                  "description": 1, 
                  "screen_name": 1, 
                  "default_profile": 1, 
                  "verified": 1, 
                  "time_zone": 1, 
                  "profile_text_color": 1, 
                  "is_translator": 1, 
                  "profile_sidebar_fill_color": 1, 
                  "location": 1, 
                  "id_str": 1, 
                  "default_profile_image": 1, 
                  "profile_background_tile": 1, 
                  "lang": 1, 
                  "friends_count": 1, 
                  "protected": 1, 
                  "favourites_count": 1, 
                  "created_at": 1, 
                  "profile_link_color": 1, 
                  "name": 1, 
                  "show_all_inline_media": 1, 
                  "follow_request_sent": 1, 
                  "geo_enabled": 1, 
                  "profile_sidebar_border_color": 1, 
                  "url": 1, 
                  "id": 1, 
                  "contributors_enabled": 1, 
                  "following": 1, 
                  "utc_offset": 1
            }, 
            "id": 1, 
            "coordinates": 1, 
            "geo": 1
      }, 
      "user": {
            "notifications": 1, 
            "profile_use_background_image": 1, 
            "statuses_count": 1, 
            "profile_background_color": 1, 
            "followers_count": 1, 
            "profile_image_url": 1, 
            "listed_count": 0, 
            "profile_background_image_url": 1, 
            "description": 1, 
            "screen_name": 1, 
            "default_profile": 1, 
            "verified": 1, 
            "time_zone": 1, 
            "profile_text_color": 1, 
            "is_translator": 1, 
            "profile_sidebar_fill_color": 1, 
            "location": 1, 
            "id_str": 1, 
            "default_profile_image": 1, 
            "profile_background_tile": 1, 
            "lang": 1, 
            "friends_count": 1, 
            "protected": 1, 
            "favourites_count": 1, 
            "created_at": 1, 
            "profile_link_color": 1, 
            "name": 1, 
            "show_all_inline_media": 1, 
            "follow_request_sent": 1, 
            "geo_enabled": 1, 
            "profile_sidebar_border_color": 1, 
            "url": 1, 
            "id": 1, 
            "contributors_enabled": 1, 
            "following": 1, 
            "utc_offset": 1
      }, 
      "id": 1, 
      "coordinates": 1, 
      "geo": 1
};

export default dataFormat;